[package]
name = "fuel-tx"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
categories = ["cryptography::cryptocurrencies", "data-structures"]
edition = "2021"
homepage = "https://fuel.network/"
keywords = ["blockchain", "cryptocurrencies", "fuel-vm", "vm"]
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuel-tx"
description = "FuelVM transaction."

[dependencies]
fuel-asm = { version = "0.1", default-features = false }
fuel-types = { version = "0.1", default-features = false }
itertools = { version = "0.10", optional = true }
rand = { version = "0.8", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
sha2 = { version = "0.9", optional = true }

[dev-dependencies]
fuel-types = { version = "0.1", default-features = false, features = ["random"] }

[features]
default = ["fuel-asm/default", "fuel-types/default", "std"]
random = ["fuel-types/random"]
std = ["fuel-asm/std", "fuel-types/std", "itertools", "rand", "sha2"]
serde-types = ["fuel-asm/serde-types", "fuel-types/serde-types", "serde-types-minimal", "serde/default", "std"]
serde-types-minimal = ["fuel-asm/serde-types-minimal", "fuel-types/serde-types-minimal", "serde"]

[[test]]
name = "test-bytes"
path = "tests/bytes.rs"
required-features = ["std"]

[[test]]
name = "test-offsets"
path = "tests/offset.rs"
required-features = ["std"]

[[test]]
name = "test-valid"
path = "tests/valid.rs"
required-features = ["std"]
