[package]
name = "fuel-tx"
version = "0.13.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
categories = ["cryptography::cryptocurrencies", "data-structures"]
edition = "2021"
homepage = "https://fuel.network/"
keywords = ["blockchain", "cryptocurrencies", "fuel-vm", "vm"]
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuel-tx"
description = "FuelVM transaction."

[dependencies]
fuel-asm = { version = "0.6", default-features = false }
fuel-crypto = { version = "0.5", default-features = false }
fuel-merkle = { version = "0.2", default-features = false, optional = true }
fuel-types = { version = "0.5", default-features = false }
itertools = { version = "0.10", default-features = false }
rand = { version = "0.8", default-features = false, features = ["std_rng"], optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
bincode = { version = "1.3", default-features = false }
fuel-crypto = { version = "0.5", default-features = false, features = ["random"] }
fuel-tx = { path = ".", features = ["builder", "random"] }
fuel-tx-test-helpers = { path = "test-helpers" }
fuel-types = { version = "0.5", default-features = false, features = ["random"] }
insta = "1.0"
proptest = "1.0"
rand = { version = "0.8", default-features = false, features = ["std_rng"] }
rstest = "0.13"

[features]
default = ["fuel-asm/default", "fuel-crypto/default", "fuel-merkle?/default", "fuel-types/default", "std"]
alloc = ["fuel-merkle", "fuel-types/alloc", "itertools/use_alloc", "serde/alloc"]
builder = ["alloc", "internals"]
internals = []
random = ["fuel-crypto/random", "fuel-types/random", "rand"]
std = ["alloc", "fuel-asm/std", "fuel-crypto/std", "fuel-merkle?/std", "fuel-types/std", "itertools/default", "rand/default", "serde?/default"]
serde = ["dep:serde", "fuel-asm/serde", "fuel-crypto/serde", "fuel-types/serde"]

[[test]]
name = "test-bytes"
path = "tests/bytes.rs"
required-features = ["serde", "std"]

[[test]]
name = "test-offsets"
path = "tests/offset.rs"
required-features = ["std"]

[[test]]
name = "test-prepared-init"
path = "tests/prepared_init.rs"
required-features = ["std"]

[[test]]
name = "test-valid"
path = "tests/valid.rs"
required-features = ["std"]
