[package]
name = "fuel-tx"
description = "FuelVM transaction."
version = "0.1.0"
authors = ["Victor Lopez <victor.lopez@fuel.sh>"]
edition = "2018"
repository = "https://github.com/FuelLabs/fuel-tx"
keywords = ["blockchain", "cryptocurrencies", "fuel-vm", "vm"]
categories = ["cryptography::cryptocurrencies", "data-structures"]

[dependencies]
fuel-asm = {git="ssh://git@github.com/FuelLabs/fuel-asm.git"}
itertools = "0.10"
sha2 = "0.9"
rand = "0.8"
